# Generated by Django 6.0.3 on 2026-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('cpp', models.IntegerField(blank=True, null=True)),
                ('b1', models.IntegerField(blank=True, null=True)),
                ('b2', models.IntegerField(blank=True, null=True)),
                ('rule', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('donorCode', models.CharField(blank=True, max_length=50, null=True)),
                ('usageStatus', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPSReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('casePerPallet', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('copackCode', models.CharField(blank=True, max_length=20)),
                ('values', models.JSONField(default=dict)),
            ],
        ),
    ]
