export const navItems = [
  { label: 'Master Data', icon: 'MD' },
  { label: 'Master Data (Refined)', icon: 'MR' },
  { label: 'MPS Report', icon: 'MP' },
  { label: 'BOM Master', icon: 'BM' },
  { label: 'BOM Master (Refined)', icon: 'BR' },
  { label: 'Donor Check', icon: 'DC' },
  { label: 'Capacity Report', icon: 'CR' },
  { label: 'MRP Report', icon: 'MRP' },
  { label: 'Copack Order Sheet', icon: 'CO' },
  { label: 'PO Sheet', icon: 'PO' },
  { label: 'Daily Pipeline Position Report', icon: 'DP' },
  { label: 'Stock Coverage Report', icon: 'SC' },
];

export const masterDataRows = [
  {
    code: '10071863',
    desc: 'CES TERRINE OF BFCHDILL 8* (3*100G)',
    cpp: 180,
    b1: 180,
    b2: 90,
    rule: 2,
    type: 'Copack',
    rate: 574,
    donorCode: 'D001',
    usageStatus: 'Active',
  },
  {
    code: '10061484',
    desc: 'SNICKERS FUNSIZE COSTCO 12*1361G',
    cpp: 180,
    b1: 180,
    b2: 90,
    rule: 3,
    type: 'Copack',
    rate: 215,
    donorCode: 'D002',
    usageStatus: 'Active',
  },
  {
    code: '10086648',
    desc: 'CESAR BEEF & CHEESE 24*100G',
    cpp: 180,
    b1: 180,
    b2: 90,
    rule: 2,
    type: 'Copack',
    rate: 496,
    donorCode: 'D003',
    usageStatus: 'Inactive',
  },
  {
    code: '10086649',
    desc: 'CESAR BEEF & CHICKEN 24*100G',
    cpp: 180,
    b1: 180,
    b2: 90,
    rule: 2,
    type: 'Standard',
    rate: 374,
    donorCode: 'D001',
    usageStatus: 'Active',
  },
  {
    code: '10086651',
    desc: 'CESAR BULGOGI 24*100G',
    cpp: 180,
    b1: 180,
    b2: 90,
    rule: 3,
    type: 'Standard',
    rate: 319,
    donorCode: 'D002',
    usageStatus: 'Inactive',
  },
  {
    code: '10086652',
    desc: 'CESAR LAMB 24*100',
    cpp: 180,
    b1: 180,
    b2: 90,
    rule: 2,
    type: 'Copack',
    rate: 268,
    donorCode: 'D003',
    usageStatus: 'Active',
  },
];
